from datetime import datetime
import csv
from html import escape
from io import StringIO
import os


def save_report(report_type, content=None, answer=None):
    """Save a markdown report in a way that supports both usages:

    save_report("code_review", result)
    save_report("file_name.py", "question", "answer")
    """

    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    repo_name = os.getenv("GITHUB_REPO", "Unknown Repository")

    if answer is not None:
        file_name = str(report_type)
        question = str(content)
        answer_text = str(answer)
        safe_file_name = file_name.replace(".", "_").replace("/", "_").replace("\\", "_")
        filename = f"reports/{safe_file_name}_{timestamp}.md"

        report = f"""
# GitHub AI Code Review Report

## Repository
{repo_name}

## File
{file_name}

## Analysis Date
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## User Question
{question}

## AI Analysis

{answer_text}

---

Generated by GitHub AI Code Assistant
"""

        with open(filename, "w", encoding="utf-8") as file:
            file.write(report)

        return filename

    if content is None:
        raise ValueError("A report body is required.")

    safe_report_type = (
        str(report_type)
        .replace(".", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )
    filename = f"reports/{safe_report_type}_{timestamp}.md"

    with open(filename, "w", encoding="utf-8") as file:
        file.write(str(content))

    return filename


def report_as_csv(report_type, content, repository="Unknown Repository"):
    """Return a report as UTF-8 CSV bytes."""
    output = StringIO(newline="")
    writer = csv.writer(output)
    writer.writerow(["Repository", "Report Type", "Analysis"])
    writer.writerow([repository, report_type, str(content)])
    return output.getvalue().encode("utf-8-sig")


def report_as_doc(report_type, content, repository="Unknown Repository"):
    """Return a Word-readable HTML document using the legacy .doc format."""
    document = f"""<html>
<head><meta charset="utf-8"><title>GitHub AI Report</title></head>
<body>
<h1>GitHub AI Engineering Report</h1>
<p><strong>Repository:</strong> {escape(str(repository))}</p>
<p><strong>Report type:</strong> {escape(str(report_type))}</p>
<h2>Analysis</h2>
<pre>{escape(str(content))}</pre>
</body>
</html>"""
    return document.encode("utf-8")